spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://database-product:3306/ecommerce_product_db?createDatabaseIfNotExist=true
    username: root
    password: 20032003Tt
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://backend-discovery-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
